import os
from dotenv import load_dotenv
load_dotenv()

print("Loaded DATABASE_URL:", os.getenv("DATABASE_URL"))

class Config:

    SECRET_KEY = os.getenv("SECRET_KEY", "fallback-secret")
    SQLALCHEMY_DATABASE_URI = os.getenv("DATABASE_URL")
    SQLALCHEMY_TRACK_MODIFICATIONS = False


    SECURITY_PASSWORD_SALT = os.getenv("SECURITY_PASSWORD_SALT", "salty-dev-key")
    SECURITY_PASSWORD_HASH = "bcrypt"

    SECURITY_REGISTERABLE = True
    SECURITY_SEND_REGISTER_EMAIL = False
    SECURITY_RECOVERABLE = False
    SECURITY_CHANGEABLE = False
    SECURITY_USERNAME_ENABLE = False
    SECURITY_TRACKABLE = True
    SECURITY_LOGIN_WITHOUT_CONFIRMATION = True

    SECURITY_LOGIN_USER_TEMPLATE = 'login.html'
    SECURITY_REGISTER_USER_TEMPLATE = 'signup.html'


    SECURITY_POST_LOGIN_VIEW = "/dashboard"
    SECURITY_POST_LOGOUT_VIEW = "/"
    SECURITY_POST_REGISTER_VIEW = "/dashboard"

   
    SECURITY_TOKEN_AUTHENTICATION_HEADER = None
    SECURITY_TOKEN_AUTHENTICATION_KEY = None

   
    SECURITY_CSRF_PROTECT_MECHANISMS = ["session"]
    SECURITY_CSRF_IGNORE_UNAUTH_ENDPOINTS = True
    WTF_CSRF_ENABLED = False
    SECURITY_JSON = True

   
    SESSION_COOKIE_NAME = "session"
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_SECURE = False
