"""Renamed due_date to deadline

Revision ID: 07a14672ddf8
Revises: 0f05180a4448
Create Date: 2025-07-16 08:43:29.306466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a14672ddf8'
down_revision = '0f05180a4448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.String(length=20), nullable=True))
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
