"""Enable cascading deletes for task analytics

Revision ID: 743847b064eb
Revises: affd313c9d5d
Create Date: 2025-07-20 19:14:41.970537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743847b064eb'
down_revision = 'affd313c9d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('analytics_log_task_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('subtask', schema=None) as batch_op:
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('subtask_task_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtask', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subtask_task_id_fkey'), 'task', ['task_id'], ['id'])
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('analytics_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('analytics_log_task_id_fkey'), 'task', ['task_id'], ['id'])

    # ### end Alembic commands ###
